import { Schema, model } from 'mongoose';
import { SiteSettingsDocumentData } from './settings.types';

const defaultPaymentMethods = [
  {
    id: 'pay_cod',
    code: 'cod',
    nameBn: 'ক্যাশ অন ডেলিভারি (পণ্য বুঝে টাকা দিন)',
    nameEn: 'Cash on Delivery (Pay when received)',
    descriptionBn: 'পণ্য হাতে পাওয়ার পর মূল্য পরিশোধ করুন',
    descriptionEn: 'Pay with cash upon delivery of your items',
    isActive: true,
    isDefault: true,
  },
  {
    id: 'pay_bkash',
    code: 'bkash',
    nameBn: 'বিকাশ (bKash Instant)',
    nameEn: 'bKash Instant Payment',
    descriptionBn: 'বিকাশ মার্চেন্ট একাউন্টে সেন্ড মানি/মেক পেমেন্ট করুন',
    descriptionEn: 'Fast & secure bKash payment',
    accountNumber: '01712345678 (Merchant)',
    instructionsBn: 'বিকাশ এপে মেক পেমেন্ট করুন ০১৭১২৩৪NTX',
    instructionsEn: 'Make payment to 01712345678',
    isActive: true,
    isDefault: false,
  },
  {
    id: 'pay_nagad',
    code: 'nagad',
    nameBn: 'নগদ (Nagad Payment)',
    nameEn: 'Nagad Instant Payment',
    descriptionBn: 'নগদ একাউন্ট থেকে পেমেন্ট করুন',
    descriptionEn: 'Secure Nagad wallet payment',
    accountNumber: '01712345678 (Merchant)',
    instructionsBn: 'নগদ মার্চেন্ট নম্বরে পেমেন্ট সম্পন্ন করুন',
    instructionsEn: 'Make payment to Nagad Merchant number',
    isActive: true,
    isDefault: false,
  },
  {
    id: 'pay_card',
    code: 'card',
    nameBn: 'কার্ড / ইন্টারনেট ব্যাংকিং (SSLCommerz)',
    nameEn: 'Visa / Mastercard / Internet Banking',
    descriptionBn: 'যে কোনো ব্যাংকের কার্ড দিয়ে তাতক্ষণিক পেমেন্ট করুন',
    descriptionEn: 'Pay via Debit/Credit Cards or Net Banking',
    isActive: true,
    isDefault: false,
  },
];

const defaultDeliveryOptions = [
  {
    id: 'del_dhaka',
    code: 'inside_dhaka',
    nameBn: 'ঢাকার ভিতরে ডেলিভারি',
    nameEn: 'Inside Dhaka City',
    charge: 60,
    estimatedDaysBn: '২৪ - ৪৮ ঘণ্টা',
    estimatedDaysEn: '24 - 48 Hours',
    descriptionBn: 'ঢাকার যে কোনো স্থানে হোম ডেলিভারি',
    descriptionEn: 'Home delivery inside Dhaka Metropolitan area',
    isActive: true,
    isDefault: true,
  },
  {
    id: 'del_outside',
    code: 'outside_dhaka',
    nameBn: 'ঢাকার বাইরে কুরিয়ার ডেলিভারি',
    nameEn: 'Outside Dhaka (All BD)',
    charge: 120,
    estimatedDaysBn: '২ - ৩ কার্যদিবস',
    estimatedDaysEn: '2 - 3 Working Days',
    descriptionBn: 'সুন্দরিবন/এসএ পরিবহন/রেডেক্স কুরিয়ার সার্ভিস',
    descriptionEn: 'Courier home delivery across Bangladesh',
    isActive: true,
    isDefault: false,
  },
  {
    id: 'del_express',
    code: 'express',
    nameBn: 'জরুরী এক্সপ্রেস ডেলিভারি (২-৬ ঘণ্টা)',
    nameEn: 'Urgent Express Delivery (Dhaka Only)',
    charge: 150,
    estimatedDaysBn: '২ - ৬ ঘণ্টা',
    estimatedDaysEn: '2 - 6 Hours',
    descriptionBn: 'ঢাকার মধ্যে জরুরি প্রয়োজনে দ্রততম প্যাথাও/রাইডার হ্যান্ডওভার',
    descriptionEn: 'Instant express courier delivery inside Dhaka',
    isActive: true,
    isDefault: false,
  },
];

const siteSettingsSchema = new Schema<SiteSettingsDocumentData>(
  {
    general: {
      siteName: { type: String, default: 'mediShop' },
      tagline: { type: String, default: 'Online Pharmacy & Healthcare BD' },
      logoLight: { type: String, default: '/images/logo.png' },
      logoDark: { type: String, default: '/images/logo.png' },
      favicon: { type: String, default: '/favicon.ico' },
      contactEmail: { type: String, default: 'support@medishop.com.bd' },
      contactPhone: { type: String, default: '+880 1742-643763' },
      address: { type: String, default: 'House 42, Road 11, Banani, Dhaka-1213, Bangladesh' },
    },
    branding: {
      primaryColor: { type: String, default: '#1D4ED8' },
      accentColor: { type: String, default: '#F59E0B' },
      fontHeading: { type: String, default: 'Inter' },
      fontBody: { type: String, default: 'Inter' },
    },
    banners: {
      type: [
        {
          id: { type: String, required: true },
          titleBn: { type: String, default: '' },
          titleEn: { type: String, required: true },
          subtitleBn: { type: String, default: '' },
          subtitleEn: { type: String, default: '' },
          badgeBn: { type: String, default: '' },
          badgeEn: { type: String, default: '' },
          ctaTextBn: { type: String, default: 'অর্ডার করুন' },
          ctaTextEn: { type: String, default: 'Order Now' },
          ctaLink: { type: String, default: '/products' },
          isActive: { type: Boolean, default: true },
          priority: { type: Number, default: 1 },
          image: { type: String, default: '' },
        },
      ],
      default: [
        {
          id: 'banner_1',
          titleEn: '100% Genuine Prescription & OTC Medicines',
          titleBn: '১০০% আসল প্রেসক্রিপশন ও ওটিসি ওষুধ',
          subtitleEn: 'Verified by registered pharmacists. Express delivery in Dhaka.',
          subtitleBn: 'রেজিস্টার্ড ফার্মাসিস্ট দ্বারা যাচাইকৃত। ঢাকায় দ্রুততম হোম ডেলিভারি।',
          badgeEn: 'DGDA Certified Pharmacy',
          badgeBn: 'ডিজিডিএ অনুমোদিত ফার্মেসি',
          ctaTextEn: 'Order Medicines',
          ctaTextBn: 'ওষুধ অর্ডার করুন',
          ctaLink: '/products',
          isActive: true,
          priority: 1,
          image: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?q=80&w=1200&auto=format&fit=crop',
        },
        {
          id: 'banner_2',
          titleEn: 'Upload Prescription for Rapid Verification',
          titleBn: 'প্রেসক্রিপশন আপলোড করে দ্রুত অর্ডার করুন',
          subtitleEn: 'Get expert guidance from clinical pharmacists in 10 mins.',
          subtitleBn: '১০ মিনিটের মধ্যে এক্সপার্ট ফার্মাসিস্টদের পরামর্শ ও অর্ডার সম্পন্ন করুন।',
          badgeEn: 'Free Pharmacist Consultation',
          badgeBn: 'ফ্রি ফার্মাসিস্ট পরামর্শ',
          ctaTextEn: 'Upload Prescription',
          ctaTextBn: 'প্রেসক্রিপশন দিন',
          ctaLink: '/prescription',
          isActive: true,
          priority: 2,
          image: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?q=80&w=1200&auto=format&fit=crop',
        },
      ],
    },
    payment: {
      codEnabled: { type: Boolean, default: true },
      minOrderForCod: { type: Number, default: 0 },
      enabledGateways: { type: [String], default: ['cod', 'bkash', 'nagad', 'card'] },
      methods: {
        type: [
          {
            id: String,
            code: String,
            nameBn: String,
            nameEn: String,
            descriptionBn: String,
            descriptionEn: String,
            accountNumber: String,
            instructionsBn: String,
            instructionsEn: String,
            icon: String,
            isActive: Boolean,
            isDefault: Boolean,
          },
        ],
        default: defaultPaymentMethods,
      },
    },
    shipping: {
      freeShippingThreshold: { type: Number, default: 1000 },
      defaultDeliveryChargeInsideDhaka: { type: Number, default: 60 },
      defaultDeliveryChargeOutsideDhaka: { type: Number, default: 120 },
      estimatedDeliveryDays: { type: String, default: '2 - 4 working days' },
      options: {
        type: [
          {
            id: String,
            code: String,
            nameBn: String,
            nameEn: String,
            charge: Number,
            estimatedDaysBn: String,
            estimatedDaysEn: String,
            descriptionBn: String,
            descriptionEn: String,
            isActive: Boolean,
            isDefault: Boolean,
          },
        ],
        default: defaultDeliveryOptions,
      },
    },
    seo: {
      defaultMetaTitle: { type: String, default: 'mediShop — Online Pharmacy BD' },
      defaultMetaDescription: {
        type: String,
        default: 'Buy authentic medicines, prescription items, & healthcare products online in Bangladesh.',
      },
      ogImage: { type: String, default: '/images/og-banner.png' },
      googleAnalyticsId: { type: String, default: '' },
      facebookPixelId: { type: String, default: '' },
    },
    legal: {
      termsContent: {
        type: String,
        default: 'Welcome to mediShop. By using our website, you agree to our terms and conditions.',
      },
      privacyContent: {
        type: String,
        default: 'We protect your personal data and health information with strict confidentiality.',
      },
      refundPolicyContent: {
        type: String,
        default: 'Returns accepted within 7 days with original seal & invoice receipt.',
      },
      invoiceTerms: {
        type: String,
        default: 'Goods once sold are non-refundable unless damaged or incorrect. DGDA verified items.',
      },
      warrantyPolicyContent: {
        type: String,
        default: 'Manufacturer warranty applies where applicable with official invoice.',
      },
    },
    maintenanceMode: { type: Boolean, default: false },
    updatedBy: { type: Schema.Types.ObjectId, ref: 'User' },
  },
  {
    timestamps: true,
  }
);

export const SiteSettingsModel = model<SiteSettingsDocumentData>('SiteSettings', siteSettingsSchema);
